on:
    push:
      branches:
        - main
        - master
    pull_request:
      branches:
        - main
        - master
  
name: Windows build
jobs:
    test-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            
            - name: Install miniconda
              uses: conda-incubator/setup-miniconda@v2
              with:
                auto-activate-base: true
                python-version: "3.11"

            - name: Install GDAL
              run: conda install -c conda-forge gdal --yes

            - name: Set GDAL environment variables
              run: |
                setx GDAL_DATA "%CONDA_PREFIX%\Library\share\gdal"
                setx PROJ_LIB "%CONDA_PREFIX%\Library\share\proj"

            - name: Add GDAL to PATH
              run: |
                setx PATH "%CONDA_PREFIX%\Library\bin;%PATH%"

            - name: Test GDAL installation
              run: |
                python -c "from osgeo import gdal"
                gdalinfo --version

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install --no-cache-dir Cython
                pip install -r requirements.txt
                pip install .
